"""sutunlari_gercekten_ekle

Revision ID: 63987293dc81
Revises: e3086a463ed1
Create Date: 2026-08-06 15:21:24.636639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63987293dc81'
down_revision: Union[str, Sequence[str], None] = 'e3086a463ed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('owner_name', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('vehicle_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'vehicle_type')
    op.drop_column('vehicles', 'owner_name')
    # ### end Alembic commands ###
